server:
  port: 5003
spring:
  application:
    name: resource-oauth2-spr

security:
  oauth2:
    client:
      client-id: 123
      client-secret: 123
      user-authorization-uri: http://localhost:5002/oauth/user
      access-token-uri: http://localhost:5002/oauth/token
    resource:
      user-info-uri: http://localhost:5002/oauth/user